#!/usr/bin/python3

import unittest

from prepare_pythonpath import prepare_pythonpath

prepare_pythonpath()

# load tests
from hotkey_drill.tests.key_combo_test import Key_combo_test
from hotkey_drill.tests.key_test import Key_test
from hotkey_drill.tests.mode_test import Mode_test

# run tests
unittest.main(verbosity=2)
